mvc_dotnet/WebApplication.Web/ViewComponents/NavBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication.Web.Providers.Auth;

namespace WebApplication.Web.ViewComponents
{
    /// <summary>
    /// A view component is a reusable or "isolated" piece of our app.
    /// It cannot be navigated to via URL like a controller.
    /// </summary>
    public class NavBarViewComponent : ViewComponent
    {
        // Components allow dependency injection just like controllers.
        private IAuthProvider authProvider;
        public NavBarViewComponent(IAuthProvider authProvider)
        {
            this.authProvider = authProvider;
        }

        /// <summary>
        /// This is the method that is invoked when the component is told to "render".
        /// </summary>
        /// <returns></returns>
        public IViewComponentResult Invoke()
        {
            var user = authProvider.GetCurrentUser();
            return View("_NavBar", user);
        }
    }
}

mvc_dotnet/WebApplication.Web/Views/Shared/_GamesListView.cshtml
@model WebApplication.Web.Models.Account.ProfileViewModel

<div class="row">
    <div class="col-sm-4 text-right">
        <select asp-for="GamesSelected" asp-items="@Model.Games" class="well-sm well"></select>
    </div>
</div>

mvc_dotnet/WebApplication.Web/Views/Shared/_GenresListView.cshtml
@model WebApplication.Web.Models.Account.ProfileViewModel

<div class="row">
    <div class="col-sm-4 text-right">
        <select asp-for="GenresSelected" asp-items="@Model.Genres" class="well-sm well"></select>
    </div>
</div>

mvc_dotnet/WebApplication.Web/Views/Shared/_Layout.cshtml
@*
    FONTS
    https://fonts.googleapis.com
    font-family: 'Roboto', sans-serif;
    font-family: 'Roboto Condensed', sans-serif;
    font-family: 'Racing Sans One', cursive;

    COLORS
    https://coolors.co
    #0F1108 - Smoky Black
    #E5E5E5 - Platinum
    #00F6ED - Turquoise BLue
    #6A07FF - Electric Indigo
    #FF00FF - Magenta
*@


<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication.Web</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link href="https://fonts.googleapis.com/css?family=Faster+One|Racing+Sans+One|Roboto|Roboto+Condensed&display=swap" rel="stylesheet">
</head>

<body id="bkg-img" class="img-responsive">
    <header>
        <div class="position">
            <h1 id="font-h1" class="text-center-fluid">MatchMadeInBETA</h1>
            <h4 id="font-h4" class="text-center-fluid">Search for and Meet like-minded Gamers in your area!</h4>
        </div>
    </header>
    <nav id="nav-text" class="navbar navbar-inverse navbar-sticky">
        <div class="container" background-color="#0F1108">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @*<a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">matchmadeinBETA</a>*@
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Help">Help</a></li>
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    @await Component.InvokeAsync("NavBar") @* Render the NavBar component. *@
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container-fluid">
        @RenderBody()
        <hr class="footer navbar-fixed-bottom" />
        <footer id="footer" class="footer navbar-fixed-bottom">
            <p>&copy; 2018 - WebApplication.Web</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>
<style scoped>

    #font-h1 {
        display: flex;
        justify-content: center;
        top:0;
        font-family: 'Racing Sans One', cursive;
        margin-top: 05px;
        color: magenta;
        font-size: 60pt;
        font-weight: bolder;
        text-shadow: 02px 02px 02px grey;
    }
    #font-h4 {
        display: flex;
        justify-content: center;
        font-family: 'Racing Sans One', cursive;
        margin-top: 10px;
        color: deepskyblue;
        font-size: 20pt;
        font-weight: normal;
       
    }
    #body-padding {
        padding-top: 20px;
    }

    #bkg-img {
        background: url(https://wallpaperaccess.com/download/retro-42337) 100% 25% no-repeat;
        background-size: cover;
    }
 
</style>